- name: Get Repo List
  id: repo
  uses: yi-Xu-0100/repo-list-generator@v1.0.1
      with:
          my_token: ${{ secrets.GITHUB_TOKEN }}
          user: ${{ github.repository }}
          max_page: 10
          block_list:
          allow_empty: false

- name: Echo Output
  run: |
      echo repo: ${{steps.repo.outputs.repo}}
      echo repoList: ${{steps.repo.outputs.repoList}}
      echo repoList_ALL: ${{steps.repo.outputs.repoList_ALL}}
      echo repoList_PRIVATE: ${{steps.repo.outputs.repoList_PRIVATE}}
      echo repoList_FORK: ${{steps.repo.outputs.repoList_FORK}}
      echo privateList: ${{steps.repo.outputs.privateList}}
      echo forkList: ${{steps.repo.outputs.forkList}}
      echo emptyList: ${{steps.repo.outputs.emptyList}}
